// Copied from polysync-design-system@9057396 build/ts/tokens.ts. Do not edit here.
// PolySync design tokens for React Native. Generated by scripts/build-tokens.mjs. Do not edit by hand.
// Dimensions are unitless points, durations are milliseconds, colours are hex.
export const tokens = {
  "dark": {
    "color": {
      "neutral": {
        "0": "#ffffff",
        "50": "#f5f7f6",
        "100": "#e9edeb",
        "200": "#d3d9d7",
        "300": "#b3bcbd",
        "400": "#8f9a9d",
        "450": "#7a8588",
        "500": "#6b7679",
        "550": "#5f6a6d",
        "600": "#4e585b",
        "700": "#353e41",
        "800": "#232b2f",
        "850": "#1c2326",
        "900": "#161c1f",
        "950": "#0e1214",
        "1000": "#070a0b"
      },
      "lime": {
        "50": "#f1fbd3",
        "100": "#e8f8b8",
        "200": "#d4f482",
        "300": "#bfe45a",
        "400": "#a2d241",
        "500": "#77a82f",
        "600": "#5b7d2a",
        "700": "#44572a",
        "800": "#3d5a14",
        "900": "#1f2913"
      },
      "mint": {
        "100": "#e2f4ec",
        "300": "#86e3bb",
        "700": "#10755a",
        "900": "#16302a"
      },
      "amber": {
        "100": "#fbf0d9",
        "300": "#f5b544",
        "700": "#5f4300",
        "900": "#35290f"
      },
      "red": {
        "100": "#fdecec",
        "300": "#f25f5f",
        "700": "#c42f35",
        "900": "#3a1c1f"
      },
      "blue": {
        "100": "#e3eefb",
        "300": "#6aa7f2",
        "700": "#1d62b5",
        "900": "#152a44"
      },
      "viz": {
        "blue": {
          "light": "#2a78d6",
          "dark": "#3987e5"
        },
        "orange": {
          "light": "#eb6834",
          "dark": "#d95926"
        },
        "aqua": {
          "light": "#1baf7a",
          "dark": "#199e70"
        },
        "yellow": {
          "light": "#eda100",
          "dark": "#c98500"
        },
        "load-light": {
          "1": "#8fb83a",
          "2": "#6f9a2c",
          "3": "#557d22",
          "4": "#3d5f17",
          "5": "#26400b"
        },
        "load": {
          "1": "#44572a",
          "2": "#5b7d2a",
          "3": "#77a82f",
          "4": "#a2d241",
          "5": "#d4f482"
        },
        "unprogrammed": "#4e585b",
        "category": {
          "strength": "#3987e5",
          "power": "#d95926",
          "endurance-hard": "#199e70",
          "endurance-easy": "#c98500"
        }
      },
      "alpha": {
        "scrim-dark": "#000000b3",
        "scrim-light": "#0e121466"
      },
      "bg": {
        "canvas": "#0e1214",
        "surface": "#161c1f",
        "surface-raised": "#1c2326",
        "surface-sunken": "#070a0b",
        "accent": "#d4f482",
        "accent-pressed": "#bfe45a",
        "accent-subtle": "#1f2913",
        "inverse": "#f5f7f6"
      },
      "text": {
        "primary": "#f5f7f6",
        "secondary": "#b3bcbd",
        "tertiary": "#8f9a9d",
        "on-accent": "#0e1214",
        "accent": "#d4f482",
        "on-accent-subtle": "#d4f482",
        "inverse": "#0e1214",
        "disabled": "#6b7679"
      },
      "border": {
        "subtle": "#232b2f",
        "strong": "#6b7679",
        "accent": "#d4f482",
        "focus": "#d4f482"
      },
      "status": {
        "good": {
          "fg": "#86e3bb",
          "bg": "#16302a"
        },
        "warning": {
          "fg": "#f5b544",
          "bg": "#35290f"
        },
        "critical": {
          "fg": "#f25f5f",
          "bg": "#3a1c1f"
        },
        "info": {
          "fg": "#6aa7f2",
          "bg": "#152a44"
        }
      },
      "readiness": {
        "ready": "#86e3bb",
        "low": "#f5b544",
        "pain": "#f25f5f"
      },
      "overlay": {
        "scrim": "#000000b3"
      }
    },
    "space": {
      "0": 0,
      "50": 2,
      "100": 4,
      "200": 8,
      "300": 12,
      "400": 16,
      "500": 20,
      "600": 24,
      "700": 32,
      "800": 40,
      "900": 48,
      "1000": 64
    },
    "radius": {
      "sm": 8,
      "md": 12,
      "lg": 16,
      "xl": 24,
      "pill": 999
    },
    "size": {
      "target-min": 44,
      "target-android": 48,
      "icon-sm": 16,
      "icon-md": 20,
      "icon-lg": 24,
      "border-hairline": 1,
      "border-strong": 2,
      "focus-ring": 3
    },
    "duration": {
      "instant": 0,
      "fast": 120,
      "fade": 150,
      "standard": 220,
      "emphasis": 320
    },
    "easing": {
      "out": [
        0,
        0,
        0.2,
        1
      ],
      "in-out": [
        0.4,
        0,
        0.2,
        1
      ],
      "linear": [
        0,
        0,
        1,
        1
      ]
    },
    "font": {
      "family": {
        "latin": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "arabic": [
          "SF Arabic",
          "IBM Plex Sans Arabic",
          "Noto Sans Arabic",
          "system-ui",
          "sans-serif"
        ],
        "mono": [
          "SF Mono",
          "ui-monospace",
          "Menlo",
          "monospace"
        ]
      },
      "weight": {
        "regular": 400,
        "medium": 500,
        "semibold": 600,
        "bold": 700
      },
      "size": {
        "caption2": 11,
        "caption1": 12,
        "footnote": 13,
        "subheadline": 15,
        "callout": 16,
        "body": 17,
        "title3": 20,
        "title2": 22,
        "title1": 28,
        "large-title": 34,
        "display": 48
      },
      "line-height": {
        "caption2": 13,
        "caption1": 16,
        "footnote": 18,
        "subheadline": 20,
        "callout": 21,
        "body": 22,
        "title3": 25,
        "title2": 28,
        "title1": 34,
        "large-title": 41,
        "display": 52
      }
    },
    "text": {
      "display": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 48,
        "lineHeight": 52,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "large-title": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 34,
        "lineHeight": 41,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "title1": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 28,
        "lineHeight": 34,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "title2": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 22,
        "lineHeight": 28,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "title3": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 20,
        "lineHeight": 25,
        "fontWeight": 600,
        "letterSpacing": 0
      },
      "headline": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 17,
        "lineHeight": 22,
        "fontWeight": 600,
        "letterSpacing": 0
      },
      "body": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 17,
        "lineHeight": 22,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "callout": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 16,
        "lineHeight": 21,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "subheadline": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 15,
        "lineHeight": 20,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "footnote": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 13,
        "lineHeight": 18,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "caption": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 12,
        "lineHeight": 16,
        "fontWeight": 500,
        "letterSpacing": 0
      }
    },
    "layout": {
      "gutter": 16,
      "stack-sm": 8,
      "stack-md": 16,
      "stack-lg": 24,
      "section": 32
    },
    "motion": {
      "press": {
        "duration": 120,
        "delay": 0,
        "timingFunction": [
          0,
          0,
          0.2,
          1
        ]
      },
      "sheet": {
        "duration": 220,
        "delay": 0,
        "timingFunction": [
          0.4,
          0,
          0.2,
          1
        ]
      },
      "reflow": {
        "duration": 320,
        "delay": 0,
        "timingFunction": [
          0.4,
          0,
          0.2,
          1
        ]
      },
      "fade": {
        "duration": 150,
        "delay": 0,
        "timingFunction": [
          0,
          0,
          1,
          1
        ]
      }
    },
    "component": {
      "button": {
        "min-height": 44,
        "radius": 12,
        "padding-x": 20,
        "gap": 8,
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 17,
          "lineHeight": 22,
          "fontWeight": 600,
          "letterSpacing": 0
        },
        "primary": {
          "bg": "#d4f482",
          "bg-pressed": "#bfe45a",
          "fg": "#0e1214"
        },
        "secondary": {
          "bg": "#1c2326",
          "fg": "#f5f7f6",
          "border": "#6b7679"
        },
        "tertiary": {
          "fg": "#d4f482"
        },
        "destructive": {
          "bg": "#1c2326",
          "fg": "#f25f5f",
          "border": "#f25f5f"
        },
        "disabled": {
          "fg": "#6b7679",
          "border": "#232b2f"
        }
      },
      "chip": {
        "min-height": 44,
        "radius": 999,
        "padding-x": 16,
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 15,
          "lineHeight": 20,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "bg": "#1c2326",
        "fg": "#f5f7f6",
        "border": "#6b7679",
        "selected": {
          "bg": "#1f2913",
          "fg": "#d4f482",
          "border": "#d4f482"
        }
      },
      "card": {
        "bg": "#161c1f",
        "border": "#232b2f",
        "radius": 16,
        "padding": 16,
        "title": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 17,
          "lineHeight": 22,
          "fontWeight": 600,
          "letterSpacing": 0
        },
        "meta": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 13,
          "lineHeight": 18,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "meta-fg": "#b3bcbd"
      },
      "tile": {
        "bg": "#161c1f",
        "value": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 28,
          "lineHeight": 34,
          "fontWeight": 700,
          "letterSpacing": 0
        },
        "value-fg": "#f5f7f6",
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "label-fg": "#b3bcbd"
      },
      "badge": {
        "radius": 999,
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "suggestion": {
          "fg": "#d4f482",
          "border": "#d4f482",
          "bg": "#161c1f"
        },
        "needs-coach": {
          "fg": "#f5b544",
          "bg": "#35290f"
        },
        "decided": {
          "fg": "#b3bcbd",
          "bg": "#070a0b"
        }
      },
      "readiness": {
        "ready": {
          "fg": "#86e3bb",
          "bg": "#16302a"
        },
        "low": {
          "fg": "#f5b544",
          "bg": "#35290f"
        },
        "pain": {
          "fg": "#f25f5f",
          "bg": "#3a1c1f"
        }
      },
      "what-changed": {
        "bg": "#161c1f",
        "rule-bar": "#6aa7f2",
        "rule-fg": "#6aa7f2",
        "rule-bg": "#152a44",
        "body-fg": "#f5f7f6"
      },
      "safety-card": {
        "bg": "#3a1c1f",
        "border": "#f25f5f",
        "title": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 20,
          "lineHeight": 25,
          "fontWeight": 600,
          "letterSpacing": 0
        },
        "title-fg": "#f5f7f6",
        "body-fg": "#f5f7f6",
        "action": {
          "bg": "#f25f5f",
          "fg": "#0e1214"
        },
        "radius": 16
      },
      "sheet": {
        "bg": "#161c1f",
        "radius": 24,
        "handle": "#6b7679",
        "scrim": "#000000b3"
      },
      "tab-bar": {
        "bg": "#161c1f",
        "border": "#232b2f",
        "item-fg": "#b3bcbd",
        "item-active-fg": "#d4f482",
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "item-min": 44
      },
      "input": {
        "bg": "#070a0b",
        "fg": "#f5f7f6",
        "placeholder": "#8f9a9d",
        "border": "#6b7679",
        "border-focus": "#d4f482",
        "radius": 12,
        "min-height": 44
      },
      "chat": {
        "radius": 16,
        "text": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 17,
          "lineHeight": 22,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "author": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "author-fg": "#b3bcbd",
        "user": {
          "bg": "#1f2913",
          "fg": "#f5f7f6"
        },
        "ai": {
          "bg": "#1c2326",
          "fg": "#f5f7f6"
        },
        "coach": {
          "bg": "#152a44",
          "fg": "#f5f7f6"
        }
      },
      "slider": {
        "track": "#6b7679",
        "fill": "#d4f482",
        "thumb": "#f5f7f6",
        "thumb-size": 44
      },
      "focus": {
        "ring": "#d4f482",
        "width": 3,
        "offset": 2
      },
      "progress": {
        "track": "#6b7679",
        "fill": "#d4f482",
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 13,
          "lineHeight": 18,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "label-fg": "#b3bcbd"
      },
      "timer": {
        "value": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 48,
          "lineHeight": 52,
          "fontWeight": 700,
          "letterSpacing": 0
        },
        "value-fg": "#f5f7f6",
        "ring": "#d4f482",
        "ring-track": "#232b2f"
      }
    }
  },
  "light": {
    "color": {
      "neutral": {
        "0": "#ffffff",
        "50": "#f5f7f6",
        "100": "#e9edeb",
        "200": "#d3d9d7",
        "300": "#b3bcbd",
        "400": "#8f9a9d",
        "450": "#7a8588",
        "500": "#6b7679",
        "550": "#5f6a6d",
        "600": "#4e585b",
        "700": "#353e41",
        "800": "#232b2f",
        "850": "#1c2326",
        "900": "#161c1f",
        "950": "#0e1214",
        "1000": "#070a0b"
      },
      "lime": {
        "50": "#f1fbd3",
        "100": "#e8f8b8",
        "200": "#d4f482",
        "300": "#bfe45a",
        "400": "#a2d241",
        "500": "#77a82f",
        "600": "#5b7d2a",
        "700": "#44572a",
        "800": "#3d5a14",
        "900": "#1f2913"
      },
      "mint": {
        "100": "#e2f4ec",
        "300": "#86e3bb",
        "700": "#10755a",
        "900": "#16302a"
      },
      "amber": {
        "100": "#fbf0d9",
        "300": "#f5b544",
        "700": "#5f4300",
        "900": "#35290f"
      },
      "red": {
        "100": "#fdecec",
        "300": "#f25f5f",
        "700": "#c42f35",
        "900": "#3a1c1f"
      },
      "blue": {
        "100": "#e3eefb",
        "300": "#6aa7f2",
        "700": "#1d62b5",
        "900": "#152a44"
      },
      "viz": {
        "blue": {
          "light": "#2a78d6",
          "dark": "#3987e5"
        },
        "orange": {
          "light": "#eb6834",
          "dark": "#d95926"
        },
        "aqua": {
          "light": "#1baf7a",
          "dark": "#199e70"
        },
        "yellow": {
          "light": "#eda100",
          "dark": "#c98500"
        },
        "load-light": {
          "1": "#8fb83a",
          "2": "#6f9a2c",
          "3": "#557d22",
          "4": "#3d5f17",
          "5": "#26400b"
        },
        "load": {
          "1": "#8fb83a",
          "2": "#6f9a2c",
          "3": "#557d22",
          "4": "#3d5f17",
          "5": "#26400b"
        },
        "unprogrammed": "#b3bcbd",
        "category": {
          "strength": "#2a78d6",
          "power": "#eb6834",
          "endurance-hard": "#1baf7a",
          "endurance-easy": "#eda100"
        }
      },
      "alpha": {
        "scrim-dark": "#000000b3",
        "scrim-light": "#0e121466"
      },
      "bg": {
        "canvas": "#f5f7f6",
        "surface": "#ffffff",
        "surface-raised": "#ffffff",
        "surface-sunken": "#e9edeb",
        "accent": "#0e1214",
        "accent-pressed": "#232b2f",
        "accent-subtle": "#f1fbd3",
        "inverse": "#0e1214"
      },
      "text": {
        "primary": "#0e1214",
        "secondary": "#4e585b",
        "tertiary": "#5f6a6d",
        "on-accent": "#d4f482",
        "accent": "#3d5a14",
        "on-accent-subtle": "#3d5a14",
        "inverse": "#f5f7f6",
        "disabled": "#8f9a9d"
      },
      "border": {
        "subtle": "#d3d9d7",
        "strong": "#6b7679",
        "accent": "#3d5a14",
        "focus": "#3d5a14"
      },
      "status": {
        "good": {
          "fg": "#10755a",
          "bg": "#e2f4ec"
        },
        "warning": {
          "fg": "#5f4300",
          "bg": "#fbf0d9"
        },
        "critical": {
          "fg": "#c42f35",
          "bg": "#fdecec"
        },
        "info": {
          "fg": "#1d62b5",
          "bg": "#e3eefb"
        }
      },
      "readiness": {
        "ready": "#10755a",
        "low": "#5f4300",
        "pain": "#c42f35"
      },
      "overlay": {
        "scrim": "#0e121466"
      }
    },
    "space": {
      "0": 0,
      "50": 2,
      "100": 4,
      "200": 8,
      "300": 12,
      "400": 16,
      "500": 20,
      "600": 24,
      "700": 32,
      "800": 40,
      "900": 48,
      "1000": 64
    },
    "radius": {
      "sm": 8,
      "md": 12,
      "lg": 16,
      "xl": 24,
      "pill": 999
    },
    "size": {
      "target-min": 44,
      "target-android": 48,
      "icon-sm": 16,
      "icon-md": 20,
      "icon-lg": 24,
      "border-hairline": 1,
      "border-strong": 2,
      "focus-ring": 3
    },
    "duration": {
      "instant": 0,
      "fast": 120,
      "fade": 150,
      "standard": 220,
      "emphasis": 320
    },
    "easing": {
      "out": [
        0,
        0,
        0.2,
        1
      ],
      "in-out": [
        0.4,
        0,
        0.2,
        1
      ],
      "linear": [
        0,
        0,
        1,
        1
      ]
    },
    "font": {
      "family": {
        "latin": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "arabic": [
          "SF Arabic",
          "IBM Plex Sans Arabic",
          "Noto Sans Arabic",
          "system-ui",
          "sans-serif"
        ],
        "mono": [
          "SF Mono",
          "ui-monospace",
          "Menlo",
          "monospace"
        ]
      },
      "weight": {
        "regular": 400,
        "medium": 500,
        "semibold": 600,
        "bold": 700
      },
      "size": {
        "caption2": 11,
        "caption1": 12,
        "footnote": 13,
        "subheadline": 15,
        "callout": 16,
        "body": 17,
        "title3": 20,
        "title2": 22,
        "title1": 28,
        "large-title": 34,
        "display": 48
      },
      "line-height": {
        "caption2": 13,
        "caption1": 16,
        "footnote": 18,
        "subheadline": 20,
        "callout": 21,
        "body": 22,
        "title3": 25,
        "title2": 28,
        "title1": 34,
        "large-title": 41,
        "display": 52
      }
    },
    "text": {
      "display": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 48,
        "lineHeight": 52,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "large-title": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 34,
        "lineHeight": 41,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "title1": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 28,
        "lineHeight": 34,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "title2": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 22,
        "lineHeight": 28,
        "fontWeight": 700,
        "letterSpacing": 0
      },
      "title3": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 20,
        "lineHeight": 25,
        "fontWeight": 600,
        "letterSpacing": 0
      },
      "headline": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 17,
        "lineHeight": 22,
        "fontWeight": 600,
        "letterSpacing": 0
      },
      "body": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 17,
        "lineHeight": 22,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "callout": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 16,
        "lineHeight": 21,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "subheadline": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 15,
        "lineHeight": 20,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "footnote": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 13,
        "lineHeight": 18,
        "fontWeight": 400,
        "letterSpacing": 0
      },
      "caption": {
        "fontFamily": [
          "-apple-system",
          "SF Pro Text",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "sans-serif"
        ],
        "fontSize": 12,
        "lineHeight": 16,
        "fontWeight": 500,
        "letterSpacing": 0
      }
    },
    "layout": {
      "gutter": 16,
      "stack-sm": 8,
      "stack-md": 16,
      "stack-lg": 24,
      "section": 32
    },
    "motion": {
      "press": {
        "duration": 120,
        "delay": 0,
        "timingFunction": [
          0,
          0,
          0.2,
          1
        ]
      },
      "sheet": {
        "duration": 220,
        "delay": 0,
        "timingFunction": [
          0.4,
          0,
          0.2,
          1
        ]
      },
      "reflow": {
        "duration": 320,
        "delay": 0,
        "timingFunction": [
          0.4,
          0,
          0.2,
          1
        ]
      },
      "fade": {
        "duration": 150,
        "delay": 0,
        "timingFunction": [
          0,
          0,
          1,
          1
        ]
      }
    },
    "component": {
      "button": {
        "min-height": 44,
        "radius": 12,
        "padding-x": 20,
        "gap": 8,
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 17,
          "lineHeight": 22,
          "fontWeight": 600,
          "letterSpacing": 0
        },
        "primary": {
          "bg": "#0e1214",
          "bg-pressed": "#232b2f",
          "fg": "#d4f482"
        },
        "secondary": {
          "bg": "#ffffff",
          "fg": "#0e1214",
          "border": "#6b7679"
        },
        "tertiary": {
          "fg": "#3d5a14"
        },
        "destructive": {
          "bg": "#ffffff",
          "fg": "#c42f35",
          "border": "#c42f35"
        },
        "disabled": {
          "fg": "#8f9a9d",
          "border": "#d3d9d7"
        }
      },
      "chip": {
        "min-height": 44,
        "radius": 999,
        "padding-x": 16,
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 15,
          "lineHeight": 20,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "bg": "#ffffff",
        "fg": "#0e1214",
        "border": "#6b7679",
        "selected": {
          "bg": "#f1fbd3",
          "fg": "#3d5a14",
          "border": "#3d5a14"
        }
      },
      "card": {
        "bg": "#ffffff",
        "border": "#d3d9d7",
        "radius": 16,
        "padding": 16,
        "title": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 17,
          "lineHeight": 22,
          "fontWeight": 600,
          "letterSpacing": 0
        },
        "meta": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 13,
          "lineHeight": 18,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "meta-fg": "#4e585b"
      },
      "tile": {
        "bg": "#ffffff",
        "value": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 28,
          "lineHeight": 34,
          "fontWeight": 700,
          "letterSpacing": 0
        },
        "value-fg": "#0e1214",
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "label-fg": "#4e585b"
      },
      "badge": {
        "radius": 999,
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "suggestion": {
          "fg": "#3d5a14",
          "border": "#3d5a14",
          "bg": "#ffffff"
        },
        "needs-coach": {
          "fg": "#5f4300",
          "bg": "#fbf0d9"
        },
        "decided": {
          "fg": "#4e585b",
          "bg": "#e9edeb"
        }
      },
      "readiness": {
        "ready": {
          "fg": "#10755a",
          "bg": "#e2f4ec"
        },
        "low": {
          "fg": "#5f4300",
          "bg": "#fbf0d9"
        },
        "pain": {
          "fg": "#c42f35",
          "bg": "#fdecec"
        }
      },
      "what-changed": {
        "bg": "#ffffff",
        "rule-bar": "#1d62b5",
        "rule-fg": "#1d62b5",
        "rule-bg": "#e3eefb",
        "body-fg": "#0e1214"
      },
      "safety-card": {
        "bg": "#fdecec",
        "border": "#c42f35",
        "title": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 20,
          "lineHeight": 25,
          "fontWeight": 600,
          "letterSpacing": 0
        },
        "title-fg": "#0e1214",
        "body-fg": "#0e1214",
        "action": {
          "bg": "#c42f35",
          "fg": "#f5f7f6"
        },
        "radius": 16
      },
      "sheet": {
        "bg": "#ffffff",
        "radius": 24,
        "handle": "#6b7679",
        "scrim": "#0e121466"
      },
      "tab-bar": {
        "bg": "#ffffff",
        "border": "#d3d9d7",
        "item-fg": "#4e585b",
        "item-active-fg": "#3d5a14",
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "item-min": 44
      },
      "input": {
        "bg": "#e9edeb",
        "fg": "#0e1214",
        "placeholder": "#5f6a6d",
        "border": "#6b7679",
        "border-focus": "#3d5a14",
        "radius": 12,
        "min-height": 44
      },
      "chat": {
        "radius": 16,
        "text": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 17,
          "lineHeight": 22,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "author": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 12,
          "lineHeight": 16,
          "fontWeight": 500,
          "letterSpacing": 0
        },
        "author-fg": "#4e585b",
        "user": {
          "bg": "#f1fbd3",
          "fg": "#0e1214"
        },
        "ai": {
          "bg": "#ffffff",
          "fg": "#0e1214"
        },
        "coach": {
          "bg": "#e3eefb",
          "fg": "#0e1214"
        }
      },
      "slider": {
        "track": "#6b7679",
        "fill": "#3d5a14",
        "thumb": "#0e1214",
        "thumb-size": 44
      },
      "focus": {
        "ring": "#3d5a14",
        "width": 3,
        "offset": 2
      },
      "progress": {
        "track": "#6b7679",
        "fill": "#3d5a14",
        "label": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 13,
          "lineHeight": 18,
          "fontWeight": 400,
          "letterSpacing": 0
        },
        "label-fg": "#4e585b"
      },
      "timer": {
        "value": {
          "fontFamily": [
            "-apple-system",
            "SF Pro Text",
            "system-ui",
            "Segoe UI",
            "Roboto",
            "sans-serif"
          ],
          "fontSize": 48,
          "lineHeight": 52,
          "fontWeight": 700,
          "letterSpacing": 0
        },
        "value-fg": "#0e1214",
        "ring": "#3d5a14",
        "ring-track": "#d3d9d7"
      }
    }
  }
} as const;

export type ThemeName = keyof typeof tokens;
export type Theme = (typeof tokens)["dark"];
